import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

/**
 * Caldim Engineering — content and auth schema, on Supabase Postgres.
 *
 * Notes on the port from SQLite:
 *
 *  - Timestamps are real `timestamptz` columns rather than epoch integers.
 *    Postgres stores them in UTC and hands back a `Date`, so every comparison
 *    in the app keeps working while the values stay readable in the Supabase
 *    table editor and in `psql`.
 *  - Booleans are real booleans, not 0/1 integers.
 *  - `content_blocks.value` and `audit_logs.meta` are `jsonb`. They were TEXT
 *    holding serialised JSON; jsonb means Postgres validates the shape on
 *    write, the columns are queryable, and Drizzle hands back parsed objects
 *    so the `JSON.parse` at every read site goes away.
 *  - Enumerated columns are real `pgEnum` types, so an invalid role or
 *    outcome is rejected by the database and not only by the application.
 *
 * Everything lives in the `public` schema and is reached over the pooled
 * Postgres connection. Row Level Security is therefore not the access-control
 * boundary — the session and CSRF guards in lib/security are. See SECURITY.md.
 */

const now = sql`now()`;

/** Sortable, unguessable primary key generated by the app (see `newId`). */
const cuid = () => text("id").primaryKey();

export const adminRole = pgEnum("admin_role", ["owner", "editor"]);
export const auditOutcome = pgEnum("audit_outcome", ["success", "failure"]);
export const mediaKind = pgEnum("media_kind", ["image", "video", "raw"]);

/** A person who can sign in to /admin. */
export const adminUsers = pgTable(
  "admin_users",
  {
    id: cuid(),
    email: text("email").notNull().unique(),
    name: text("name").notNull(),
    /** argon2id digest — never a reversible encryption of the password. */
    passwordHash: text("password_hash").notNull(),
    role: adminRole("role").notNull().default("editor"),
    /** Forces a password change at next sign-in (true for the seeded account). */
    mustChangePassword: boolean("must_change_password").notNull().default(false),
    disabled: boolean("disabled").notNull().default(false),

    /** TOTP secret, AES-256-GCM encrypted at rest with APP_ENCRYPTION_KEY. */
    totpSecret: text("totp_secret"),
    totpEnabled: boolean("totp_enabled").notNull().default(false),
    /** JSON array of argon2id hashes — single-use recovery codes. */
    totpRecoveryHashes: text("totp_recovery_hashes"),

    failedAttempts: integer("failed_attempts").notNull().default(0),
    lockedUntil: timestamp("locked_until", { withTimezone: true }),
    lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
    passwordChangedAt: timestamp("password_changed_at", { withTimezone: true })
      .notNull()
      .default(now),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({ emailIdx: index("admin_users_email_idx").on(table.email) })
);

/**
 * A signed-in browser. The raw token never touches the database — only its
 * SHA-256 digest — so a database leak cannot be replayed as a live session.
 */
export const sessions = pgTable(
  "sessions",
  {
    id: cuid(),
    tokenHash: text("token_hash").notNull().unique(),
    userId: text("user_id")
      .notNull()
      .references(() => adminUsers.id, { onDelete: "cascade" }),

    /** Set once the second factor has been satisfied (or when 2FA is off). */
    fullyAuthenticated: boolean("fully_authenticated").notNull().default(false),

    ipHash: text("ip_hash"),
    userAgent: text("user_agent"),

    /** Idle timeout — bumped on each authenticated request. */
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().default(now),
    /** Absolute timeout — never extended, however active the session is. */
    absoluteExpiresAt: timestamp("absolute_expires_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({
    userIdx: index("sessions_user_idx").on(table.userId),
    expiryIdx: index("sessions_expiry_idx").on(table.expiresAt),
  })
);

/**
 * Editable site copy, addressed by a stable key (e.g. "hero", "services").
 * `value` is jsonb, validated against a Zod schema on write *and* on read.
 */
export const contentBlocks = pgTable("content_blocks", {
  key: text("key").primaryKey(),
  value: jsonb("value").notNull(),
  updatedById: text("updated_by_id"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(now),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
});

/**
 * An uploaded asset, stored in Cloudinary.
 *
 * The bytes are no longer on our disk. What we keep is the identity of the
 * remote object — `publicId` plus `resourceType`, which together address it in
 * every Cloudinary API — and enough metadata to render, sort and audit it
 * without a round trip. `secureUrl` is cached for convenience, but delivery
 * URLs are rebuilt from `publicId` so transformations can be applied.
 */
export const mediaAssets = pgTable(
  "media_assets",
  {
    id: cuid(),
    /** Cloudinary public_id, e.g. "caldim/media/lz3k2-9f1c". */
    publicId: text("public_id").notNull().unique(),
    /** Which Cloudinary API family owns it: image, video, or raw. */
    resourceType: mediaKind("resource_type").notNull().default("image"),
    /** Delivery format Cloudinary settled on: webp, mp4, pdf… */
    format: text("format").notNull().default(""),
    secureUrl: text("secure_url").notNull(),

    originalName: text("original_name").notNull(),
    mimeType: text("mime_type").notNull(),
    byteSize: integer("byte_size").notNull(),
    width: integer("width"),
    height: integer("height"),
    /** Seconds, for video and audio. Null for stills. */
    duration: real("duration"),

    /** SHA-256 of the bytes we uploaded — integrity check and dedupe key. */
    checksum: text("checksum").notNull(),
    altText: text("alt_text").notNull().default(""),
    title: text("title").notNull().default(""),

    uploadedById: text("uploaded_by_id").references(() => adminUsers.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({
    checksumIdx: index("media_assets_checksum_idx").on(table.checksum),
    kindIdx: index("media_assets_kind_idx").on(table.resourceType),
    createdIdx: index("media_assets_created_idx").on(table.createdAt),
  })
);

/** A member of the leadership team, shown in "Meet Our Leadership". */
export const leaders = pgTable(
  "leaders",
  {
    id: cuid(),
    name: text("name").notNull(),
    title: text("title").notNull(),
    credentials: text("credentials").notNull().default(""),
    bio: text("bio").notNull().default(""),
    location: text("location").notNull().default(""),
    email: text("email"),
    linkedinUrl: text("linkedin_url"),
    photoId: text("photo_id").references(() => mediaAssets.id, { onDelete: "set null" }),
    /** Fallback initials, used until a photo has been uploaded. */
    initials: text("initials").notNull().default(""),
    sortOrder: integer("sort_order").notNull().default(0),
    published: boolean("published").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({ orderIdx: index("leaders_order_idx").on(table.sortOrder) })
);

/**
 * A photo or video placed in a named slot on the public site — the project
 * gallery, the shop-floor reel, a service backdrop.
 *
 * This is what makes the media library useful rather than merely a folder:
 * an editor uploads an asset, then puts it somewhere. `collection` names the
 * slot, and the section that renders it queries by that name.
 */
export const galleryItems = pgTable(
  "gallery_items",
  {
    id: cuid(),
    /** Slot on the site: "gallery", "projects", "shopfloor", "certificates". */
    collection: text("collection").notNull().default("gallery"),
    mediaId: text("media_id")
      .notNull()
      .references(() => mediaAssets.id, { onDelete: "cascade" }),
    caption: text("caption").notNull().default(""),
    /** Shown under the caption — project name, location, tonnage. */
    meta: text("meta").notNull().default(""),
    /** Poster still for a video item; ignored for photos. */
    posterId: text("poster_id").references(() => mediaAssets.id, { onDelete: "set null" }),
    sortOrder: integer("sort_order").notNull().default(0),
    published: boolean("published").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({
    collectionIdx: index("gallery_items_collection_idx").on(table.collection, table.sortOrder),
  })
);

/** Append-only record of every privileged action. */
export const auditLogs = pgTable(
  "audit_logs",
  {
    id: cuid(),
    userId: text("user_id").references(() => adminUsers.id, { onDelete: "set null" }),
    actorInfo: text("actor_info").notNull().default(""),
    action: text("action").notNull(),
    entity: text("entity").notNull().default(""),
    entityId: text("entity_id").notNull().default(""),
    outcome: auditOutcome("outcome").notNull().default("success"),
    ipHash: text("ip_hash"),
    userAgent: text("user_agent"),
    meta: jsonb("meta"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({
    createdIdx: index("audit_logs_created_idx").on(table.createdAt),
    actionIdx: index("audit_logs_action_idx").on(table.action),
  })
);

/**
 * Fixed-window counters backing the rate limiter. Persisted rather than held
 * in memory, so a restart doesn't reset an attacker's budget and the limit
 * still holds across every worker and every serverless instance — which
 * matters more on Supabase than it did behind a single SQLite file.
 */
export const rateLimits = pgTable(
  "rate_limits",
  {
    key: text("key").primaryKey(),
    count: integer("count").notNull().default(0),
    windowStart: timestamp("window_start", { withTimezone: true }).notNull().default(now),
    blockedUntil: timestamp("blocked_until", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({ windowIdx: index("rate_limits_window_idx").on(table.windowStart) })
);

/** Submissions from the public RFQ form — stored so a mail outage loses nothing. */
export const contactSubmissions = pgTable(
  "contact_submissions",
  {
    id: cuid(),
    name: text("name").notNull(),
    company: text("company").notNull(),
    email: text("email").notNull(),
    role: text("role").notNull().default(""),
    projectType: text("project_type").notNull().default(""),
    tonnage: text("tonnage").notNull().default(""),
    timeline: text("timeline").notNull().default(""),
    message: text("message").notNull().default(""),
    attachmentId: text("attachment_id").references(() => mediaAssets.id, {
      onDelete: "set null",
    }),
    ipHash: text("ip_hash"),
    userAgent: text("user_agent"),
    handled: boolean("handled").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(now),
  },
  (table) => ({ createdIdx: index("contact_submissions_created_idx").on(table.createdAt) })
);

// ─── Relations ───────────────────────────────────────────────────────────

export const adminUsersRelations = relations(adminUsers, ({ many }) => ({
  sessions: many(sessions),
  uploads: many(mediaAssets),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(adminUsers, { fields: [sessions.userId], references: [adminUsers.id] }),
}));

export const leadersRelations = relations(leaders, ({ one }) => ({
  photo: one(mediaAssets, { fields: [leaders.photoId], references: [mediaAssets.id] }),
}));

export const galleryItemsRelations = relations(galleryItems, ({ one }) => ({
  media: one(mediaAssets, { fields: [galleryItems.mediaId], references: [mediaAssets.id] }),
  poster: one(mediaAssets, { fields: [galleryItems.posterId], references: [mediaAssets.id] }),
}));

export const mediaAssetsRelations = relations(mediaAssets, ({ one, many }) => ({
  uploadedBy: one(adminUsers, {
    fields: [mediaAssets.uploadedById],
    references: [adminUsers.id],
  }),
  leaders: many(leaders),
  galleryItems: many(galleryItems),
}));

// ─── Inferred row types ──────────────────────────────────────────────────

export type AdminUser = typeof adminUsers.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type Leader = typeof leaders.$inferSelect;
export type MediaAsset = typeof mediaAssets.$inferSelect;
export type GalleryItem = typeof galleryItems.$inferSelect;
export type AuditLogRow = typeof auditLogs.$inferSelect;
export type ContactSubmission = typeof contactSubmissions.$inferSelect;
export type MediaKind = (typeof mediaKind.enumValues)[number];
