import QRCode from "qrcode";
import { getAdminUsersCollection, getSessionsCollection } from "@/backend/db";
import { audit } from "@/backend/security/audit";
import { verifyCsrf } from "@/backend/security/csrf";
import { jsonError, jsonOk } from "@/backend/security/guard";
import { verifyPassword } from "@/backend/security/password";
import { getSession, revokeAllSessions } from "@/backend/security/session";
import {
  decryptSecret,
  encryptSecret,
  generateRecoveryCodes,
  generateTotpSecret,
  totpUri,
  verifyTotpCode,
} from "@/backend/security/totp";
import { totpEnrolSchema } from "@/backend/security/validation";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Two-factor enrolment.
 *
 *   GET    — mint a candidate secret and return a QR code to scan.
 *   POST   — confirm with a live code, switch 2FA on, hand back recovery codes.
 *   DELETE — turn 2FA off, re-authenticating with the password first.
 *
 * The candidate secret is stored encrypted but with `totpEnabled` still false,
 * so an abandoned enrolment can never lock anyone out: nothing takes effect
 * until a code generated by the user's own device proves the secret arrived.
 */

export async function GET() {
  const auth = await getSession({ requireFullAuth: false });
  if (!auth) return jsonError("Sign in to continue.", 401);
  if (auth.user.totpEnabled) return jsonError("Two-factor authentication is already on.", 409);

  const secret = generateTotpSecret();
  const adminUsers = await getAdminUsersCollection();
  await adminUsers.updateOne(
    { _id: auth.user.id },
    { $set: { totpSecret: encryptSecret(secret), updatedAt: new Date() } }
  );

  const qrDataUrl = await QRCode.toDataURL(totpUri(secret, auth.user.email), {
    margin: 1,
    width: 320,
    color: { dark: "#0B0F14", light: "#FFFFFF" },
  });

  return jsonOk({ qrDataUrl, manualKey: secret });
}

export async function POST(request: Request) {
  if (verifyCsrf(request)) {
    return jsonError("Request rejected. Reload the page and try again.", 403);
  }

  const auth = await getSession({ requireFullAuth: false });
  if (!auth) return jsonError("Sign in to continue.", 401);
  if (auth.user.totpEnabled) return jsonError("Two-factor authentication is already on.", 409);
  if (!auth.user.totpSecret) return jsonError("Start the setup again — no pending secret found.", 409);

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return jsonError("Malformed request.", 400);
  }

  const parsed = totpEnrolSchema.safeParse(body);
  if (!parsed.success) return jsonError("Enter the 6-digit code from your authenticator app.", 400);

  const secret = decryptSecret(auth.user.totpSecret);
  if (!secret || !verifyTotpCode(secret, parsed.data.code)) {
    await audit({
      action: "totp.challenge.failure",
      outcome: "failure",
      userId: auth.user.id,
      meta: { stage: "enrol" },
    });
    return jsonError("That code wasn't accepted. Check your device's clock and try again.", 400);
  }

  const { codes, hashes } = await generateRecoveryCodes();
  const adminUsers = await getAdminUsersCollection();
  await adminUsers.updateOne(
    { _id: auth.user.id },
    { $set: { totpEnabled: true, totpRecoveryHashes: hashes, updatedAt: new Date() } }
  );

  // The session that just enrolled has now satisfied both factors.
  const sessions = await getSessionsCollection();
  await sessions.updateOne(
    { _id: auth.session.id },
    { $set: { fullyAuthenticated: true } }
  );

  await audit({ action: "totp.enrolled", userId: auth.user.id, actorInfo: auth.user.email });

  // Returned exactly once — only the hashes are kept.
  return jsonOk({ recoveryCodes: codes, next: "/admin" });
}

export async function DELETE(request: Request) {
  if (verifyCsrf(request)) {
    return jsonError("Request rejected. Reload the page and try again.", 403);
  }

  const auth = await getSession();
  if (!auth) return jsonError("Sign in to continue.", 401);

  let body: { password?: string };
  try {
    body = (await request.json()) as { password?: string };
  } catch {
    return jsonError("Malformed request.", 400);
  }

  // Removing a security control is exactly the moment to re-check identity —
  // it stops a borrowed, unlocked laptop from becoming a permanent foothold.
  if (!body.password || !(await verifyPassword(auth.user.passwordHash, body.password))) {
    await audit({ action: "totp.disabled", outcome: "failure", userId: auth.user.id });
    return jsonError("That password wasn't recognised.", 401);
  }

  const adminUsers = await getAdminUsersCollection();
  await adminUsers.updateOne(
    { _id: auth.user.id },
    { $set: { totpEnabled: false, totpSecret: null, totpRecoveryHashes: null, updatedAt: new Date() } }
  );
  await revokeAllSessions(auth.user.id, auth.session.id);

  await audit({ action: "totp.disabled", userId: auth.user.id, actorInfo: auth.user.email });
  return jsonOk({ disabled: true });
}

